export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const REGISTERATION_REQUEST = "REGISTERATION_REQUEST";
export const REGISTERATION_SUCCESS = "REGISTERATION_SUCCESS";
export const REGISTERATION_FAIL = "REGISTERATION_FAIL";


export const SUBMIT_PROFILE_REQUEST = "SUBMIT_PROFILE_REQUEST";
export const SUBMIT_PROFILE_SUCCESS = "SUBMIT_PROFILE_SUCCESS";
export const SUBMIT_PROFILE_FAIL = "SUBMIT_PROFILE_FAIL";

export const LOGOUT_ADMIN_REQUEST = "LOGOUT_ADMIN_REQUEST";
export const LOGOUT_ADMIN_SUCCESS = "LOGOUT_ADMIN_SUCCESS";
export const LOGOUT_ADMIN_FAIL = "LOGOUT_ADMINE_FAIL";
